name: tool_base_test
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  tool_base:
    git:
      url: git://github.com/ivan-horchakov/tool_base.git
      ref: master
#  tool_base:
#    path: ../tool_base
  reporting:
    git:
      url: git://github.com/ivan-horchakov/reporting.git
      ref: master
#    path: ../reporting

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  mockito: ^4.1.0
